# Gradle JVM settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Kotlin
kotlin.code.style=official

# AndroidX (REQUIRED)
android.useAndroidX=true
android.enableJetifier=true

# Optional (stability + performance)
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=false
